### PR TITLE
First half of the requested german translation

### PR DESCRIPTION
**Pull request by DennisPS**
Will do more as soon as I find the time.

### CODE REVIEW

**Comment by chriscar** [comment]
Thanks! I speak german as well, very good translation so far.

**Comment by weddingdj** [comment]
@Senuros IdeaSpaceVR release v1.0.1 is out. Would you be interested in continuing the german translation?

**Comment by amuedespacher** [comment]
I could contribute as well; German is my mother tongue.

**Comment by weddingdj** [comment]
That would be great. Are you familiar with localization in Laravel?

**Pull request merged**
